# Generated by Django 3.1.4 on 2021-03-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughtbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughts',
            old_name='user',
            new_name='owner',
        ),
    ]
